#!/bin/sh
NAME="pcp-streamer"
DESC="Line-in streaming server"
[ -f /usr/local/bin/tcpserver ] && DAEMON=/usr/local/bin/tcpserver
LOG="/var/log/pcp_streamer.log"
OPTIONS="-c 1 -R 0 9100 /usr/local/bin/pcp-stream.sh"

case "$1" in
	start)
		echo "Starting $DESC: $NAME..."
		sudo -E -b $DAEMON $OPTIONS 2> $LOG
		;;
	stop)
		echo "Stopping $DESC: $NAME..."
		pgrep -f $DAEMON | xargs kill -9
		;;
	restart)
		echo "Restarting $DESC..."
		pgrep -f $DAEMON | xargs kill -9
		sleep 3
		sudo -E -b $DAEMON $OPTIONS 2> $LOG
		;;
	status)
		busybox ps -ef | grep $DAEMON | grep -v grep | awk '{ print $0 }'
		;;
	*)
		echo ""
		echo -e "Usage: /usr/local/etc/init.d/`basename $0` [start|stop|restart|status]"
		echo ""
		exit 1
		;;
esac

exit 0
