#!/bin/bash

TCZ=pcp-base.tcz
TCZINFO=${TCZ}.info
VERSION=4.0.0


BASEWD=$(pwd)
EXT="pcp-base"
TCZ=${EXT}.tcz
TCZINFO=${TCZ}.info
cd ../../pcp/${EXT}


echo "fixing directory access rights"
find -type d | xargs chmod -v 755
find * -not -type d | xargs dos2unix
find usr/local/bin -not -type d | xargs chmod 755
find usr/local/etc/init.d -not -type d | xargs chmod 755
find * -not -type d > ${BASEWD}/${TCZ}.list
cd ..

mksquashfs ${EXT} ${TCZ} -all-root -noappend 2>&1 >/dev/null
mv ${TCZ}* ${BASEWD}/

cd ${BASEWD}
md5sum ${TCZ} > ${TCZ}.md5.txt

echo "$EXT contains"
unsquashfs -ll ${TCZ}

echo -e "Title:          $TCZ" > $TCZINFO
echo -e "Description:    piCorePlayer Base Scripts." >> $TCZINFO
echo -e "Version:        $VERSION" >> $TCZINFO
echo -e "Author:         Various, see script files" >> $TCZINFO
echo -e "Original-site:" >> $TCZINFO
echo -e "Copying-policy: See scripts for details" >> $TCZINFO
echo -e "Size:           $(ls -lh $TCZ | awk '{print $5}')k" >> $TCZINFO
echo -e "Extension_by:   piCorePlayer team: https://www.picoreplayer.org" >> $TCZINFO
echo -e "Comments:       Compiled for piCore 9.x" >> $TCZINFO

echo
