#!/bin/bash

TCZ="firmware-allo-piano.tcz"
TCZINFO=${TCZ}.info
#Create the require .dep.pcp file even if no dependancy is needed....see below
PCPDEP=${TCZ}.dep.pcp
SITE="https://github.com/allocom/piano-firmware"
VERSION=3.20

BASEWD=$(pwd)

git clone $SITE --depth 1

cd piano-firmware
rm -f README.md

echo "fixing directory access rights"
find -type d | xargs chmod -v 755
find * -not -type d > ${BASEWD}/${TCZ}.list

VERSION="$(cat lib/firmware/allo/piano/VERSION)"
cd ..

mksquashfs piano-firmware ${TCZ} -all-root -noappend
#mv ${TCZ}* ${BASEWD}/

md5sum ${TCZ} > ${TCZ}.md5.txt

echo -e "Title:\t\t$TCZ" > $TCZINFO
echo -e "Description:\tFirmware for Allo Piano Dac Plus" >> $TCZINFO
echo -e "Version:\t$VERSION" >> $TCZINFO
echo -e "Author:\t\tVarious, see script files" >> $TCZINFO
echo -e "Original-site:\t${SITE}" >> $TCZINFO
echo -e "Copying-policy:\t/lib/firmware/allo/piano/LICENSE" >> $TCZINFO
echo -e "Size:\t\t$(ls -lh $TCZ | awk '{print $5}')" >> $TCZINFO
echo -e "Extension_by:\tpiCorePlayer team: https://sites.google.com/site/picoreplayer" >> $TCZINFO
echo -e "\t\tCompiled for piCore 8.x" >> $TCZINFO

echo "BOGUS.tcz" > ${PCPDEP}

rm -rf piano-firmware

echo
while true; do
   read -p "Do you want to upload to sourceforge project-web [y/n]? " yn
   case $yn in
      [Yy]* ) break;;
      [Nn]* ) exit 0;;
      * ) echo "Please answer yes or no.";;
   esac
done

REPO="web.sourceforge.net"
LOCATION_v6="/home/project-web/picoreplayer/htdocs/tcz_repo/8.x/armv6/tcz/"
LOCATION_v7="/home/project-web/picoreplayer/htdocs/tcz_repo/8.x/armv7/tcz/"

read -p "Enter your sourceforge username: " USER
# Would need to use linux expect to use passwords
# read -ps "Enter your password: " PASS

echo
echo "Ready to upload"
echo "USER=${USER}"
echo "REPO=${REPO}"
echo "LOCATION_v6=${LOCATION_v6}"
echo "LOCATION_v7=${LOCATION_v7}"
echo
read -p "Press Enter to continue, or <ctrl>-C to abort" key

echo "Uploading to first location."
scp ${TCZ}* ${USER}@${REPO}:${LOCATION_v6}
echo
echo "Uploading to second location."
scp ${TCZ}* ${USER}@${REPO}:${LOCATION_v7}

echo "Note: if this is a new extension, login to sourceforge ssh session and run script"
echo "/home/project-web/picoreplayer/htdocs/tcz_repo/8.x/create_repo_files"
echo "This step is required to get it to show in the extension browser."
echo
