#!/bin/sh

BASEWD=$(pwd)
EXT="pcp-apmode"
TCZ=${EXT}.tcz
TCZINFO=${TCZ}.info

cd $EXT
echo "fixing directory access rights"
find -type d | xargs chmod -v 755
find * -not -type d | xargs dos2unix
find * -not -type d > ${BASEWD}/${TCZ}.list
cd ..

mksquashfs ${EXT} ${TCZ} -all-root -noappend 2>&1 >/dev/null

cd ${BASEWD}
md5sum ${TCZ} > ${TCZ}.md5.txt

echo "$EXT contains"
unsquashfs -ll ${TCZ}

echo
while true; do
	read -p "Do you want to upload to sourceforge project-web [y/n]? " yn
	case $yn in
		[Yy]* ) break;;
		[Nn]* ) exit 0;;
		* ) echo "Please answer yes or no.";;
	esac
done

REPO="web.sourceforge.net"
LOCATION_v6="/home/project-web/picoreplayer/htdocs/tcz_repo/9.x/armv6/tcz/"
LOCATION_v7="/home/project-web/picoreplayer/htdocs/tcz_repo/9.x/armv6/tcz/"

read -p "Enter your sourceforge username: " USER
# Would need to use linux expect to use passwords
# read -ps "Enter your password: " PASS

echo
echo "Ready to upload"
echo "USER=${USER}"
echo "REPO=${REPO}"
echo "LOCATION_v6=${LOCATION_v6}"
echo "LOCATION_v7=${LOCATION_v7}"
echo
read -p "Press Enter to continue, or <ctrl>-C to abort" key

echo "Uploading to first location."
scp $EXT.tcz* ${USER}@${REPO}:${LOCATION_v6}
echo
echo "Uploading to second location."
scp $EXT.tcz* ${USER}@${REPO}:${LOCATION_v7}





