#!/bin/sh
# First start webserver httpd and then also add it to do_rebootstuff

pCPHOME=/home/tc/www/cgi-bin

. $pCPHOME/pcp-functions
pcp_variables

#Start web server NOW
sudo /usr/local/etc/init.d/httpd start

#Toggle # on and off in do_rebootstuff.sh
sed -i 's/\#*\/usr\/local\/etc\/init.d\/httpd start/\/usr\/local\/etc\/init.d\/httpd start/g' $pCPHOME/do_rebootstuff.sh

#Save changes
pcp_backup