#!/bin/sh
echo " "
showMenu () {
echo "1)  Download and update Squeezelite Player"
echo "2)  Use Audio from 3.5 jack, with default settings"
echo "3)  Enable HDMI audio output (a reboot is needed)"
echo "4)  Disable HDMI audio output (a reboot is needed)"
echo "5)  Get a get a list of available ALSA device. If you will use a USB-DAC please insert first"
echo "6)  Change Squeezelite settings - like name and other settings"
echo " "
echo "7)  Restart Squeezelite with the new settings"
echo " "
echo "8)  Setup wifi"
echo "9)  Reboot - If you need to"
echo "10) Make a backup of your changes"
echo "11) Disable Web-server (for Web-Gui)"
echo "12) Enable Web-server (Enabled by default for easy Web-Gui configuration - use IP-address:8077 (ie 192.128.1.12:8077)"
echo "13) Exit menu program"




}



while [ 1 ]
do
showMenu
read CHOICE
case "$CHOICE" in

"1")
echo "Download and Update Squeezeplayer"
sudo rm -rf /mnt/mmcblk0p2/tce/squeezelite-armv6hf
wget http://ralph_irving.users.sourceforge.net/pico/squeezelite-armv6hf -P /mnt/mmcblk0p2/tce
#wget http://squeezelite.googlecode.com/files/squeezelite-armv6hf -P /mnt/mmcblk0p2/tce
sudo chmod 755 /mnt/mmcblk0p2/tce/squeezelite-armv6hf
sudo filetool.sh -b
echo "  "
echo "  "
;;




"2")
echo "Use analog audio from 3.5 jack"
#Read from config file.
. /usr/local/sbin/config.cfg
ALSA_PARAMS="80:::0"
ALSA_PARAMS="\"${ALSA_PARAMS}"\"    

echo "Optimal Alsa settings for analog audio is now set to: $ALSA_PARAMS"
sudo sed -i "s/\(ALSA_PARAMS *=*\).*/\1$ALSA_PARAMS/" /usr/local/sbin/config.cfg
OUTPUT="sysdefault:CARD=ALSA"
OUTPUT="\"${OUTPUT}"\"    
echo
echo "Outut device for analog audio is now set to: $OUTPUT"
sudo sed -i "s/\(OUTPUT *=*\).*/\1$OUTPUT/" /usr/local/sbin/config.cfg
sudo filetool.sh -b
echo "  "
echo "  "
;;


"3")
echo "Enable HDMI audio output - (a reboot is needed)"
#sudo mount /dev/mmcblk0p1
#sed -i '/hdmi_drive=2/d' /mnt/mmcblk0p1/config.txt
#sudo echo hdmi_drive=2 >> /mnt/mmcblk0p1/config.txt
#sudo filetool.sh -b

#Read from config file.
. /usr/local/sbin/config.cfg
ALSA_PARAMS="-a ::32:0"

ALSA_PARAMS="\"${ALSA_PARAMS}"\"    
echo "Optimal Alsa settings for HDMI is now set to: $ALSA_PARAMS"
sudo sed -i "s/\(ALSA_PARAMS *=*\).*/\1$ALSA_PARAMS/" /usr/local/sbin/config.cfg
#sudo umount /dev/mmcblk0p1
#sudo filetool.sh -b
sudo /mnt/mmcblk0p2/tce/OliWeb-master/ivySox/myweb/enablehdmi.sh
echo "  "
echo "  "
;;


"4")
echo "Disable HDMI output - (a reboot is needed)"
#sudo mount /dev/mmcblk0p1
#sed -i '/hdmi_drive=2/d' /mnt/mmcblk0p1/config.txt
#echo "  "
#echo "  "
#sudo umount /dev/mmcblk0p1
sudo /mnt/mmcblk0p2/tce/OliWeb-master/ivySox/myweb/disablehdmi.sh
;;


"5")
echo "Press ENTER to get a list of available ALSA device, please insert USB-DAc first if you want to use it"
sudo /mnt/mmcblk0p2/tce/squeezelite-armv6hf -l
echo "  "
echo "  "
;;

"6")
echo " "
echo " "
echo " "
echo "Change the settings for Squeezelite like name etc." 
echo "If using HDMI or analog be please keep the alsa settings"
sudo /usr/local/sbin/settings_menu.sh
echo "  "
echo "  "
;;


"7")
echo "Restart Squeezelite with the new settings"
sudo /usr/local/etc/init.d/squeezelite_initd stop
sleep 2
sudo /usr/local/etc/init.d/squeezelite_initd start
echo "  "
echo "  "
;;

"8")
echo "Setup WiFi"
rm -f /home/tc/wifi.db
sudo ifconfig wlan0 down
sudo sleep 1
sudo ifconfig wlan0 up
sudo iwconfig wlan0 power off &>/dev/null
sudo sleep 1
sudo /usr/local/bin/wifi.sh
sudo /usr/local/sbin/set_wifi.sh
sudo filetool.sh -b
echo "  "
echo "  "
;;



"9")
echo "Reboot"
# here it ask for a reboot
while true; do
read -p "Do you wish to reboot? y/n" yn
case $yn in
[Yy]* ) sudo reboot; break;;
[Nn]* ) break;;
* ) echo "Please answer yes or no.";;
esac
done
;;

"10")
echo "make a backup to save additional changes"
sudo filetool.sh -b
echo "  "
echo "  "
;;


"11")
echo "Disable automatic start of Web-Server"
#change the line which starts the Web-server by adding # infront
sed -i "/usr\/local\/etc\/init.d\/oliweb_initd start/c\#usr\/local\/etc\/init.d\/oliweb_initd start" /opt/bootlocal.sh
sudo filetool.sh -b
echo "  "
echo "  "
;;


"12")
echo "Enable automatic start of Web-Server"
#change the line which starts the Web-server by removing # infront
sed -i "/usr\/local\/etc\/init.d\/oliweb_initd start/c\usr\/local\/etc\/init.d\/oliweb_initd start" /opt/bootlocal.sh
sudo filetool.sh -b
echo "  "
echo "  "
;;



"13")

exit


esac
done


