#!/bin/sh

# Version: 7.0.0 2020-05-08

. pcp-functions
. pcp-lms-functions
. pcp-pastebin-functions

pcp_html_head "Show pCP log files" "GE"

pcp_controls
pcp_diagnostics
pcp_httpd_query_string

COLUMN1="col-12"
BUTTON="btn btn-primary w-50"
#========================================================================================
# piCorePlayer log files should be located in the $LOGDIR directory (default /var/log).
#
# Log filenames need to be formatted correctly:
#  - start with "pcp_"
#  - end in ".log"
#
# i.e. pcp_diagnostics.log
#
# Note:
#  LMS log filenames do not follow this standard and are located in /var/log/slimserver.
#----------------------------------------------------------------------------------------

#========================================================================================
# Copy log files from persistent locations to $LOGDIR directory
#----------------------------------------------------------------------------------------
pcp_mount_bootpart >/dev/null 2>&1
cp ${BOOTMNT}/pcp_*.log $LOGDIR >/dev/null 2>&1
pcp_umount_bootpart >/dev/null 2>&1
cp ${TCEMNT}/tce/pcp_*.log $LOGDIR >/dev/null 2>&1
#----------------------------------------------------------------------------------------

#========================================================================================
# Create additional log files
#----------------------------------------------------------------------------------------
dmesg > ${LOGDIR}/pcp_dmesg.log
pcp_lms_players "squeezelite" "pCP" | sed 's/,/ - /g' | sort > ${LOGDIR}/pcp_squeezelite_ip.log
${SQLT_BIN} -h > ${LOGDIR}/pcp_squeezelite_help.log
${SQLT_BIN} -t > ${LOGDIR}/pcp_squeezelite_license.log
cat /usr/local/etc/pcp/pcp.cfg > ${LOGDIR}/pcp_pcp_configuration.log
#----------------------------------------------------------------------------------------

PCPLOGS=$(ls "$LOGDIR" | grep pcp_ | grep log)
[ x"" != x"$PCPLOGS" ] && LOGS=$PCPLOGS

CWD=$(pwd)
LMSLOGS=$(cd "${LOGDIR}"; ls slimserver/*.log)
cd $CWD
[ x"" != x"$LMSLOGS" ] && LOGS=${LOGS}" "$LMSLOGS
[ x"" = x"$LOGS" ] && FIRST="No log files found." || FIRST="All"

if [ $DEBUG -eq 1 ]; then
	pcp_debug_variables "html" QUERY_STRING SELECTION ACTION LOGDIR BOOTMNT TCEMNT PCPLOGS LMSLOGS LOGS
fi

#========================================================================================
# Log selection form
#----------------------------------------------------------------------------------------
pcp_heading5 "Log file operations"

#----------------------------------------------------------------------------------------
echo '  <form name="log" action="'$0'" method="get">'
echo '    <div class="row">'
echo '      <div class="col-3">'
echo '        <select class="large22" name="SELECTION">'
echo '          <option value="'$FIRST'">'$FIRST'</option>'

	            for LOG in $LOGS
	            do
	                [ "$LOG" = "$SELECTION" ] && SEL=" selected" || SEL=""
	                LOGNAME=$(echo ${LOG:4} | sed -e 's/.log//' -e 's/[._]/ /g')
	                echo '                    <option value="'$LOG'"'$SEL'>'$LOGNAME'</option>'
	            done

echo '        </select>'
echo '      </div>'
pcp_incr_id
echo '      <div class="col-9">'
echo '        <p>Select log file(s) to show&nbsp;&nbsp;'
echo '          <a type="button" data-toggle="collapse" data-target="#dt'$ID'">'$HELPBADGE'</a>'
echo '        </p>'
echo '        <div id="dt'$ID'" class="collapse">'
echo '          <p>Log files are generated by visiting the various diagnostics pages.</p>'
echo '          <p>Log files prefixed with "slimserver" are LMS log files (LMS needs to be on).</p>'
echo '          <p><b>Note:</b> Log files are temporary, they are not preserved after a reboot.</p>'
echo '        </div>'
echo '      </div>'
#----------------------------------------------------------------------------------------
if [ "$FIRST" = "All" ]; then
	echo '      <div class="col-3 mb-3">'
	echo '        <button type="submit" class="'$BUTTON'" name="ACTION" value="Show">Show</button>'
	echo '      </div>'
fi
#----------------------------------------------------------------------------------------
echo '    </div>'
echo '  </form>'
#----------------------------------------------------------------------------------------

#------------------------------------------Log text area---------------------------------
pcp_log_show() {
	echo '  <div class="col-12">'

	if [ "$SELECTION" = "All" ]; then
		for LOG in $LOGS
		do
			pcp_textarea "$LOG" 'cat ${LOGDIR}/$LOG | sed "s///g" | sed "s/\x0d//g" | sed -r "s/\[([0-9]{1,2}(;[0-9]{1,2}?)?)?[m|K]//g"' 250
		done
	else
		pcp_textarea "$SELECTION" 'cat ${LOGDIR}/$SELECTION | sed "s///g" | sed "s/\x0d//g" | sed -r "s/\[([0-9]{1,2}(;[0-9]{1,2}?)?)?[m|K]//g"' 250
	fi

	echo '  </div>'

	if [ ! "$SELECTION" = "All" ]; then
		LOG=${LOGDIR}/${SELECTION}
		[ $MODE -ge $MODE_PLAYER ] && pcp_pastebin_button $SELECTION
	fi
}
[ "$ACTION" = "Show" ] && pcp_log_show
#----------------------------------------------------------------------------------------

pcp_html_end