#!/bin/sh

# Version: 6.0.0 2019-07-07

. pcp-functions
. pcp-lms-functions
. pcp-pastebin-functions

pcp_html_head "Show pCP log files" "GE"

pcp_banner
pcp_diagnostics
pcp_httpd_query_string

#========================================================================================
# piCorePlayer log files should be located in the $LOGDIR directory (default /var/log).
#
# Log filenames need to be formatted correctly:
#  - start with "pcp_"
#  - end in ".log"
#
# i.e. pcp_diagnostics.log
#
# Note:
#  LMS log filenames do not follow this standard and are located in /var/log/slimserver.
#----------------------------------------------------------------------------------------

#========================================================================================
# Copy log files from persistent locations to /var/log/
#----------------------------------------------------------------------------------------
pcp_mount_bootpart >/dev/null 2>&1
cp ${BOOTMNT}/pcp_*.log $LOGDIR >/dev/null 2>&1
pcp_umount_bootpart >/dev/null 2>&1
cp ${TCEMNT}/tce/pcp_*.log $LOGDIR >/dev/null 2>&1
#----------------------------------------------------------------------------------------

#========================================================================================
# Create log files
#----------------------------------------------------------------------------------------
dmesg > ${LOGDIR}/pcp_dmesg.log
pcp_lms_players squeezelite pCP | sed 's/,/ - /g' | sort > ${LOGDIR}/pcp_squeezelite_ip.log
${SQLT_BIN} -h > ${LOGDIR}/pcp_squeezelite_help.log
cat /usr/local/etc/pcp/pcp.cfg > ${LOGDIR}/pcp_pcp_configuration.log
#----------------------------------------------------------------------------------------

PCPLOGS=$(ls "$LOGDIR" | grep pcp_ | grep log)
[ x"" != x"$PCPLOGS" ] && LOGS=$PCPLOGS

CWD=$(pwd)
LMSLOGS=$(cd "${LOGDIR}"; ls slimserver/*.log)
cd $CWD
[ x"" != x"$LMSLOGS" ] && LOGS=${LOGS}" "$LMSLOGS
[ x"" = x"$LOGS" ] && FIRST="No log files found." || FIRST="All"

if [ $DEBUG -eq 1 ]; then
	echo '<!-- Start of debug info -->'
	pcp_table_top "debug"
	pcp_debug_variables "html" SELECTION ACTION LOGDIR BOOTMNT TCEMNT PCPLOGS LMSLOGS LOGS
	pcp_table_end
	echo '<!-- End of debug info -->'
fi

#========================================================================================
# Log selection form
#----------------------------------------------------------------------------------------
echo '<table class="bggrey">'
echo '  <tr>'
echo '    <td>'
echo '      <div class="row">'
echo '        <fieldset>'
echo '          <legend>Log file operations</legend>'
echo '          <form name="log" action="'$0'" method="get">'
echo '            <table class="bggrey percent100">'
#----------------------------------------------------------------------------------------
pcp_incr_id
pcp_start_row_shade
echo '              <tr class="'$ROWSHADE'">'
echo '                <td class="column300">'
echo '                  <select class="large22" name="SELECTION">'
echo '                    <option value="'$FIRST'">'$FIRST'</option>'

	                      for LOG in $LOGS
	                      do
	                          [ "$LOG" = "$SELECTION" ] && SEL=" selected" || SEL=""
	                          LOGNAME=$(echo ${LOG:4} | sed -e 's/.log//' -e 's/[._]/ /g')
	                          echo '                    <option value="'$LOG'"'$SEL'>'$LOGNAME'</option>'
	                      done

echo '                  </select>'
echo '                </td>'
echo '                <td>'
echo '                  <p>Select log file(s) to show&nbsp;&nbsp;'
echo '                    <a id="'$ID'a" class="moreless" href=# onclick="return more('\'''$ID''\'')">more></a>'
echo '                  </p>'
echo '                  <div id="'$ID'" class="less">'
echo '                    <p>Log files are generated by visiting the various diagnostics pages.</p>'
echo '                    <p>Log files prefixed with "slimserver" are LMS log files (LMS needs to be on).</p>'
echo '                    <p><b>Note:</b> Log files are temporary, they are not preserved after a reboot.</p>'
echo '                  </div>'
echo '                </td>'
echo '              </tr>'

if [ "$FIRST" = "All" ]; then
	pcp_toggle_row_shade
	echo '              <tr class="'$ROWSHADE'">'
	echo '                <td colspan="2">'
	echo '                  <input type="submit" name="ACTION" value="Show">'
	echo '                </td>'
	echo '              </tr>'
fi

#----------------------------------------------------------------------------------------
echo '            </table>'
echo '          </form>'
echo '        </fieldset>'
echo '      </div>'
echo '    </td>'
echo '  </tr>'
echo '</table>'
#----------------------------------------------------------------------------------------

#------------------------------------------Log text area---------------------------------
pcp_log_show() {
	pcp_table_top "Show log file(s)"

	if [ "$SELECTION" = "All" ]; then
		for LOG in $LOGS
		do
			pcp_textarea_inform "$LOG" 'cat ${LOGDIR}/$LOG | sed "s///g" | sed "s/\x0d//g" | sed -r "s/\[([0-9]{1,2}(;[0-9]{1,2}?)?)?[m|K]//g"' 250
		done
	else
		pcp_textarea_inform "$SELECTION" 'cat ${LOGDIR}/$SELECTION | sed "s///g" | sed "s/\x0d//g" | sed -r "s/\[([0-9]{1,2}(;[0-9]{1,2}?)?)?[m|K]//g"' 250
	fi

	pcp_table_end

	if [ ! "$SELECTION" = "All" ]; then
		LOG=${LOGDIR}/${SELECTION}
		[ $MODE -ge $MODE_BETA ] && pcp_pastebin_button $SELECTION
	fi
}
[ "$ACTION" = "Show" ] && pcp_log_show
#----------------------------------------------------------------------------------------

pcp_footer
pcp_copyright

echo '</body>'
echo '</html>'
exit