#!/bin/sh

# This page is meant to be embedded in an IFRAME

. pcp-functions
. pcp-lms-functions

pcp_html_head "NowPlaying" "PH"

[ x"" = x"$LMSWEBPORT" ] && LMSPORT=9000 || LMSPORT=$LMSWEBPORT
LMSIP=$(pcp_lmsip)

echo '<body onload=loadImage()>'
echo '  <table class="nowplaying">'
echo '    <tr>'
echo '      <td class="column100">'
echo '        <img id="image" src="" width="96" height="96"/>'
echo '      </td>'
echo '      <td class="column400">'
echo '        <table class="nowplayingtxt">'
echo '          <tr >'
echo '            <td colspan=2 id="track"></td>'
echo '          </tr>'
echo '          <tr></tr>'
echo '          <tr >'
echo '            <td colspan=2 id="artist"></td>'
echo '           </tr>'
echo '          <tr >'
echo '            <td class="column300" id="album"></td>'
echo '            <td id="time">'
echo '            </td>'
echo '          </tr>'
echo '        </table>'
echo '      </td>'
echo '    </tr>'
echo '  </table>'

echo '<script>'
echo '  window.setInterval("loadImage();", 5000);'
echo '  function formatTime(seconds) {'
echo '    const h = Math.floor(seconds / 3600);'
echo '    const m = Math.floor((seconds % 3600) / 60);'
echo '    const s = seconds % 60;'
echo '    return ['
echo '      h,'
echo '      m > 9 ? m : (h ? "0" + m : m || "0"),'
echo '      s > 9 ? s : "0" + s,'
echo '      ].filter(a => a).join(":");'
echo '  }'
echo '  var xhttp = null;'
echo '  function loadImage() {'
echo '    xhttp = new XMLHttpRequest()'
echo '    xhttp.onreadystatechange = function() {'
echo '      if (this.readyState == 4 && this.status == 200) {'
echo '        var myObj = JSON.parse(this.responseText);'
echo '        var url = "http://'$LMSIP':'${LMSPORT}'"'
echo '        if (myObj.result.remoteMeta != null) {'
echo '          document.getElementById("image").src = url.concat(myObj.result.remoteMeta.artwork_url);'
echo '          document.getElementById("track").innerHTML = myObj.result.remoteMeta.title;'
echo '          document.getElementById("artist").innerHTML = myObj.result.remoteMeta.artist;'
echo '          document.getElementById("album").innerHTML = myObj.result.remoteMeta.album;'
echo '        } else if (myObj.result.playlist_loop["0"].artwork_track_id  != null ) {'
echo '          var id = myObj.result.playlist_loop["0"].artwork_track_id;'
echo '          document.getElementById("image").src = url.concat("/music/" + id + "/cover.jpg");'
echo '          document.getElementById("track").innerHTML = myObj.result.playlist_loop["0"].title;'
echo '          if ( myObj.result.playlist_loop["0"].artist != null) {'
echo '            document.getElementById("artist").innerHTML = myObj.result.playlist_loop["0"].artist;'
echo '          } else {'
echo '          document.getElementById("artist").innerHTML = myObj.result.playlist_loop["0"].albumartist;'
echo '          }'
echo '          document.getElementById("album").innerHTML = myObj.result.playlist_loop["0"].album;'
echo '        };'
echo '        var duration = formatTime(Math.round(myObj.result.duration));'
echo '        var tracktime = formatTime(Math.round(myObj.result.time));'
echo '        var stringtime = tracktime.toString();'
echo '        document.getElementById("time").innerHTML = stringtime.concat("/", duration.toString());'
echo '      } else {'
echo '        document.getElementById("track").innerHTML = "Upgrade to LMS 7.9.2 for proper function";'
echo '        document.getElementById("artist").innerHTML = "";'
echo '        document.getElementById("album").innerHTML = "";'
echo '      }'
echo '    };'
echo '    xhttp.open("POST", "http://'$LMSIP':'${LMSPORT}'/jsonrpc.js", true);'
echo '    xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");'
echo '    var data = {"id":1,"method":"slim.request","params": [ "'$NAME'", [ "status", "-", "1", "tags:cgABbehldiqtyrSuoKLNJ" ]]}'
echo '    var jsondata = JSON.stringify(data);'
echo '    xhttp.send(jsondata);'
echo '  }'
echo '</script>'
echo '</body>'
echo '</html>'
