#!/bin/sh
# pcp-pastebin-functions
# These are the common Pastebin functions used by piCorePlayer.

# Version: 5.0.0 2019-03-03

pcp_debug_log "$0 - Running pcp-pastebin-functions..."

#========================================================================================
# References:
# - https://pastebin.com/api
# - http://stackoverflow.com/questions/296536/how-to-urlencode-data-for-curl-command
#----------------------------------------------------------------------------------------

#========================================================================================
# Default API settings
#----------------------------------------------------------------------------------------
API_DEV_KEY="2aec56fbd1e156783c02ae91d6c57bc5"
API_USER_NAME="pCP"
API_USER_PASSWORD="picoreplayer1234"
API_PASTE_PRIVATE="2"
API_PASTE_NAME="$(pcp_rpi_shortname)"
API_PASTE_EXPIRE_DATE="1D"
PBWGET="/usr/local/bin/wget"

#. pcp-rpi-functions   <--- REMEMBER THIS GE

#========================================================================================
# wget routine - Check for wget.tcz and download and install.
#----------------------------------------------------------------------------------------
pcp_install_wget() {
	echo '<textarea class="inform" rows="4">'
	ls /usr/local/tce.installed/wget
	if [ $? -eq 0 ]; then
		echo 'wget.tcz already installed.'
	else
		if [ ! -f $TCEMNT/tce/optional/wget.tcz ]; then
			echo 'wget.tcz downloading... '
			sudo -u tc pcp-load -r ${PCP_REPO} -w wget.tcz
			[ $? -eq 0 ] && echo 'Done.' || echo 'Error.'
		else
			echo 'wget.tcz downloaded.'
		fi
		echo 'wget.tcz installing... '
		sudo -u tc tce-load -i wget.tcz
		[ $? -eq 0 ] && echo 'Done.' || echo 'Error.'
	fi
	echo '</textarea>'
}

#========================================================================================
# Pastebin button.
#----------------------------------------------------------------------------------------
pcp_pastebin_button() {
	if [ $MODE -ge $MODE_BETA ]; then
		echo '<table class="bggrey">'
		echo '  <tr>'
		echo '    <td>'
		echo '      <div class="row">'
		echo '        <form name="Paste" action="pastebin.cgi" method="get">'
		echo '          <div class="row">'
		echo '            <fieldset>'
		echo '              <legend>Upload to Pastebin</legend>'
		echo '              <table class="bggrey percent100">'
		pcp_start_row_shade
		echo '                <tr class="'$ROWSHADE'">'
		echo '                  <td class="column150 center">'
		echo '                    <input type="submit" name="SUBMIT" value="Upload">'
		echo '                    <input type="hidden" name="FILE" value="'$LOG'">'
		echo '                    <input type="hidden" name="REPORT" value="'${1}'">'
		echo '                  </td>'
		echo '                  <td>'
		echo '                    <p>Upload to Pastebin.</p>'
		echo '                  </td>'
		echo '                </tr>'
		echo '              </table>'
		echo '            </fieldset>'
		echo '          </div>'
		echo '        </form>'
		echo '      </div>'
		echo '    </td>'
		echo '  </tr>'
		echo '</table>'
	fi
}

#========================================================================================
# Get api_user_key.
#----------------------------------------------------------------------------------------
pcp_pastebin_get_api_user_key() {
	POST_DATA="api_dev_key=$API_DEV_KEY"
	POST_DATA=$POST_DATA"&api_user_name=$API_USER_NAME"
	POST_DATA=$POST_DATA"&api_user_password=$API_USER_PASSWORD"

	[ $DEBUG -eq 1 ] && [ $TEST -eq 4 ] && echo '<p class="debug">[ DEBUG ] $POST_DATA: '$POST_DATA'</p>'
	API_USER_KEY=$($PBWGET -O - --tries=5 --timeout=60 --post-data=$POST_DATA 'https://pastebin.com/api/api_login.php')
	[ $DEBUG -eq 1 ] && echo '<p class="debug">[ DEBUG ] $API_USER_KEY: '$API_USER_KEY'</p>'
}

#========================================================================================
# Paste text to Pastebin.
#----------------------------------------------------------------------------------------
pcp_pastebin_paste() {
	pcp_pastebin_get_api_user_key

	API_POST_CODE=$API_POST_CODE
	API_PASTE_NAME="$(pcp_rpi_shortname)-${2}"

	POST_DATA="api_option=paste"
	POST_DATA=$POST_DATA"&api_dev_key=$API_DEV_KEY"
	POST_DATA=$POST_DATA"&api_paste_code=$API_POST_CODE"
	POST_DATA=$POST_DATA"&api_paste_expire_date=$API_PASTE_EXPIRE_DATE"
	POST_DATA=$POST_DATA"&api_paste_private=$API_PASTE_PRIVATE"
	POST_DATA=$POST_DATA"&api_paste_name=$API_PASTE_NAME"
	POST_DATA=$POST_DATA"&api_user_key=$API_USER_KEY"

	[ $DEBUG -eq 1 ] && [ $TEST -eq 4 ] && echo '<p class="debug">[ DEBUG ] $POST_DATA: '$POST_DATA'</p>'
	echo '<p class="info">[ INFO ] Uploading '$FILE' to Pastebin...</p>'
	PASTEBIN_URL=$($PBWGET -O - --tries=5 --timeout=60 --post-data=$POST_DATA 'https://pastebin.com/api/api_post.php')
}

#========================================================================================
# Listing Pastes Created By A User - NOT USED.
#----------------------------------------------------------------------------------------
pcp_pastebin_get_listing() {
	pcp_pastebin_get_api_user_key

	POST_DATA="api_option=list"
	POST_DATA=$POST_DATA"&api_dev_key=$API_DEV_KEY"
	POST_DATA=$POST_DATA"&api_user_key=$API_USER_KEY"
	POST_DATA=$POST_DATA"&api_results_limit=10"

	LISTING_LOG=/tmp/pcp_pastebin_listing.log

	$($PBWGET -O $LISTING_LOG --tries=5 --timeout=60 --post-data=$POST_DATA 'https://pastebin.com/api/api_post.php')

	cat $LISTING_LOG
}
