#!/bin/sh +x
# pcp-pastebin-functions
# These are the common pastebin functions used by piCorePlayer

# Version: 0.02 2016-01-28 GE
#	Changed pastebin button to developer mode.

# Version: 0.01 2015-12-24 GE
#	Original.

#========================================================================================
# References:
# - http://pastebin.com/api
# - http://stackoverflow.com/questions/296536/how-to-urlencode-data-for-curl-command
#----------------------------------------------------------------------------------------

#========================================================================================
# Default API settings
#----------------------------------------------------------------------------------------
API_DEV_KEY="2aec56fbd1e156783c02ae91d6c57bc5"
API_USER_NAME="pCP"
API_USER_PASSWORD="picoreplayer1234"
API_PASTE_PRIVATE="2"
API_PASTE_NAME="$(pcp_rpi_shortname)"
API_PASTE_EXPIRE_DATE="1D"
WGET="/usr/local/bin/wget"

#========================================================================================
# urlencode is not installed by default in piCore/piCorePlayer so here is a ash hack.
#----------------------------------------------------------------------------------------
. pcp-rpi-functions
pcp_pastebin_encoding() {
	local string="${1}"
	local strlen=${#string}
	local encoded=""
	local pos=0

	while [ $pos -lt $strlen ]
	do
		c="${string:$pos:1}"
		case "$c" in
			[-_.~a-zA-Z0-9])
				o="${c}"
				;;
			*)
#				o=%$(echo -n "${c}" | hexdump -e '/1 "%02x"')
				o=$( printf "%%%02X" "'${c}")
				;;
		esac
		encoded=$encoded"${o}"
		pos=$(($pos + 1))
#		echo -n ${c}
	done
	echo "${encoded}" 
}

#========================================================================================
# wget routine - Check for wget.tcz and download and install
#----------------------------------------------------------------------------------------
pcp_install_wget() {
	echo '<textarea class="inform" rows="4">'
	ls /usr/local/tce.installed/wget
	if [ $? = 0 ]; then
		echo 'wget.tcz already installed.'
	else
		if [ ! -f /mnt/mmcblk0p2/tce/optional/wget.tcz ]; then
			echo 'wget.tcz downloading... '
			sudo -u tc tce-load -w wget.tcz
			[ $? = 0 ] && echo 'Done.' || echo 'Error.'
		else
			echo 'wget.tcz downloaded.'
		fi
		echo 'wget.tcz installing... '
		sudo -u tc tce-load -i wget.tcz
		[ $? = 0 ] && echo 'Done.' || echo 'Error.'
	fi
	echo '</textarea>'
}

#========================================================================================
# pCP pastebin button
#----------------------------------------------------------------------------------------
pcp_pastebin_button() {
	if [ $MODE -ge $MODE_DEVELOPER ]; then
		echo '<table class="bggrey">'
		echo '  <tr>'
		echo '    <td>'
		echo '      <div class="row">'
		echo '        <form name="Paste" action="pastebin.cgi" method="get">'
		echo '          <div class="row">'
		echo '            <fieldset>'
		echo '              <legend>Upload</legend>'
		echo '              <table class="bggrey percent100">'
		pcp_start_row_shade
		echo '                <tr class="'$ROWSHADE'">'
		echo '                  <td class="column150 center">'
		echo '                    <input type="submit" name="SUBMIT" value="Upload" />'
		echo '                    <input type="hidden" name="FILE" value="'$LOG'" />'
		echo '                    <input type="hidden" name="REPORT" value="'${1}'" />'
		echo '                  </td>'
		echo '                  <td>'
		echo '                    <p>Upload report to pastebin.</p>'
		echo '                  </td>'
		echo '                </tr>'
		echo '              </table>'
		echo '            </fieldset>'
		echo '          </div>'
		echo '        </form>'
		echo '      </div>'
		echo '    </td>'
		echo '  </tr>'
		echo '</table>'
	fi
}

#========================================================================================
# Get api_user_key
#----------------------------------------------------------------------------------------
pcp_pastebin_get_api_user_key() {
	POST_DATA="api_dev_key=$API_DEV_KEY"
	POST_DATA=$POST_DATA"&api_user_name=$API_USER_NAME"
	POST_DATA=$POST_DATA"&api_user_password=$API_USER_PASSWORD"

	[ $DEBUG = "1" ] && echo '<p class="debug">[ DEBUG ] Post data: '$POST_DATA'</p>'
	API_USER_KEY=$($WGET -O - --tries=5 --timeout=60 --post-data=$POST_DATA 'http://pastebin.com/api/api_login.php')
	[ $DEBUG = "1" ] && echo '<p class="debug">[ DEBUG ] api_user_key: '$API_USER_KEY'</p>'
}

#========================================================================================
# Paste text to pastebin
#----------------------------------------------------------------------------------------
pcp_pastebin_paste() {
	pcp_pastebin_get_api_user_key

	[ $DEBUG = "1" ] && echo '<p class="debug">[ DEBUG ] Encoding '$1', please wait...</p>'
	API_POST_CODE=$(cat ${1})
	API_POST_CODE=$(pcp_pastebin_encoding "$API_POST_CODE")
	API_PASTE_NAME="${API_PASTE_NAME}-${2}"

	POST_DATA="api_option=paste"
	POST_DATA=$POST_DATA"&api_dev_key=$API_DEV_KEY"
	POST_DATA=$POST_DATA"&api_paste_code=$API_POST_CODE"
	POST_DATA=$POST_DATA"&api_paste_expire_date=$API_PASTE_EXPIRE_DATE"
	POST_DATA=$POST_DATA"&api_paste_private=$API_PASTE_PRIVATE"
	POST_DATA=$POST_DATA"&api_paste_name=$API_PASTE_NAME"
	POST_DATA=$POST_DATA"&api_user_key=$API_USER_KEY"

	[ $DEBUG = "1" ] && echo '<p class="debug">[ DEBUG ] Post data: '$POST_DATA'</p>'
	[ $DEBUG = "1" ] && echo '<p class="debug">[ DEBUG ] Uploading '$1', please wait...</p>'
	PASTEBIN_URL=$($WGET -O - --tries=5 --timeout=60 --post-data=$POST_DATA 'http://pastebin.com/api/api_post.php')
	[ $DEBUG = "1" ] && echo '<p class="debug">[ DEBUG ] url: '$PASTEBIN_URL'</p>'
}

#========================================================================================
# Listing Pastes Created By A User
#----------------------------------------------------------------------------------------
pcp_pastebin_get_listing() {
	pcp_pastebin_get_api_user_key

	POST_DATA="api_option=list"
	POST_DATA=$POST_DATA"&api_dev_key=$API_DEV_KEY"
	POST_DATA=$POST_DATA"&api_user_key=$API_USER_KEY"
	POST_DATA=$POST_DATA"&api_results_limit=10"

	LISTING_LOG=/tmp/pcp_pastebin_listing.log

	$($WGET -O $LISTING_LOG --tries=5 --timeout=60 --post-data=$POST_DATA 'http://pastebin.com/api/api_post.php')

	cat $LISTING_LOG
}
