#!/bin/sh
# pcp-rpi-functions
# These are the common Raspberry Pi functions used by piCorePlayer

# Version: 0.01 2014-10-22 GE
#	Original.

#=========================================================================================
# Determine revisions and features of Raspberry Pi
#-----------------------------------------------------------------------------------------
# References:
# http://elinux.org/RPi_HardwareHistory#Board_Revision_History
# http://www.raspberrypi.org/forums/viewtopic.php?f=63&t=32733&p=301930&hilit=revision+identification&sid=e70960c27964330d9677de2eff077b80#p301930
# http://raspberryalphaomega.org.uk/2013/02/06/automatic-raspberry-pi-board-revision-detection-model-a-b1-and-b2/
#-----------------------------------------------------------------------------------------
pcp_rpi_revision() {
	awk -F: '/^Revision/ { print $2 }' /proc/cpuinfo | sed 's/ //g'
}

pcp_rpi_details() {
	case $(pcp_rpi_revision) in
		*Beta) MODEL=B;  PCBREV=Beta; MEMORY=256;;
		*0002) MODEL=B;  PCBREV=1;    MEMORY=256;;
		*0003) MODEL=B;  PCBREV=1+;   MEMORY=256;;
		*0004) MODEL=B;  PCBREV=2;    MEMORY=256;;
		*0005) MODEL=B;  PCBREV=2;    MEMORY=256;;
		*0006) MODEL=B;  PCBREV=2;    MEMORY=256;;
		*0007) MODEL=A;  PCBREV=2;    MEMORY=256;;
		*0008) MODEL=A;  PCBREV=2;    MEMORY=256;;
		*0009) MODEL=A;  PCBREV=2;    MEMORY=256;;
		*0010) MODEL=B+; PCBREV=1.2;  MEMORY=512;;
		*0011) MODEL=CM; PCBREV=1.0;  MEMORY=512;;
		*000d) MODEL=B;  PCBREV=2;    MEMORY=512;;
		*000e) MODEL=B;  PCBREV=2;    MEMORY=512;;
		*000f) MODEL=B;  PCBREV=2;    MEMORY=512;;
		*)     MODEL=?;  PCBREV=?;    MEMORY=?;;
	esac

	case $MODEL$PCBREV in
		*B1)   ETHER=1; USB=2; LED=5; P2PINS=1; HOLES=0; PIN3=0; PIN5=1; PIN13=21; I2C=0; P5=0; P6=0;;
		*B1+)  ETHER=1; USB=2; LED=5; P2PINS=0; HOLES=0; PIN3=0; PIN5=1; PIN13=21; I2C=0; P5=0; P6=0;;
		*B2)   ETHER=1; USB=2; LED=5; P2PINS=0; HOLES=2; PIN3=1; PIN5=2; PIN13=27; I2C=1; P5=8; P6=2;;
		*A)    ETHER=0; USB=1; LED=2; P2PINS=0; HOLES=2; PIN3=1; PIN5=2; PIN13=27; I2C=1; P5=8; P6=2;;
		*B+*)  ETHER=1; USB=4; LED=2; P2PINS=0; HOLES=4; PIN3=X; PIN5=X; PIN13=X;  I2C=X; P5=X; P6=X;;
		*CM*)  ETHER=0; USB=0; LED=X; P2PINS=0; HOLES=0; PIN3=X; PIN5=X; PIN13=X;  I2C=X; P5=X; P6=X;;
		*)     ETHER=X; USB=X; LED=X; P2PINS=X; HOLES=X; PIN3=X; PIN5=X; PIN13=X;  I2C=X; P5=X; P6=X;;
	esac
}

#=========================================================================================
# Model
#-----------------------------------------------------------------------------------------
pcp_rpi_model() {
	pcp_rpi_details
	echo $MODEL
}

pcp_rpi_is_model_A() {
	pcp_rpi_details
	[ $MODEL = A ] && echo 0 || echo 1
}

pcp_rpi_is_model_B() {
	pcp_rpi_details
	[ $MODEL = B ] && echo 0 || echo 1
}

pcp_rpi_is_model_B_rev_1() {
	pcp_rpi_details
	([ $MODEL = B ] && [ $PCBREV = 1 ]) && echo 0 || echo 1
}

pcp_rpi_is_model_B_rev_2() {
	pcp_rpi_details
	([ $MODEL = B ] && [ $PCBREV = 2 ]) && echo 0 || echo 1
}

pcp_rpi_is_model_Bplus() {
	pcp_rpi_details
	[ $MODEL = B+ ] && echo 0 || echo 1
}

pcp_rpi_is_model_CM() {
	pcp_rpi_details
	[ $MODEL = CM ] && echo 0 || echo 1
}

#=========================================================================================
# Revision
#-----------------------------------------------------------------------------------------
pcp_rpi_pcb_revision() {
	pcp_rpi_details
	echo $PCBREV
}

#=========================================================================================
# Memory
#-----------------------------------------------------------------------------------------
pcp_rpi_memory() {
	pcp_rpi_details
	echo $MEMORY
}

pcp_rpi_is_memory_256() {
	pcp_rpi_details
	[ $MEMORY = 256 ] && echo 0 || echo 1
}

pcp_rpi_is_memory_512() {
	pcp_rpi_details
	[ $MEMORY = 512 ] && echo 0 || echo 1
}