#!/bin/sh

# Version: 0.01 2015-03-10 GE
#   Original version.

. pcp-lms-functions
. pcp-functions
pcp_variables
. $CONFIGCFG

pcp_html_head "xtras_asound_conf" "GE"

pcp_controls
pcp_banner
pcp_navigation
pcp_mode_lt_99
pcp_running_script

#========================================================================================
# Write asound.conf
#----------------------------------------------------------------------------------------
#VOLUMERIGHT=1
#VOLUMELEFT=1

pcp_write_asound_conf() {
	echo '# Generated by piCorePlayer'  >$ASOUNDCONF
	echo 'pcm.!default {'              >>$ASOUNDCONF
	echo '	type route'                >>$ASOUNDCONF
	echo '	slave.pcm hw'              >>$ASOUNDCONF

	case $OPTION in
		mono)
			echo '	# mono 0 = left, 1 = right' >>$ASOUNDCONF
			echo '	ttable {'                   >>$ASOUNDCONF
			echo '		0.1 '$VOLLEFT           >>$ASOUNDCONF
			echo '		0.0 '$VOLLEFT           >>$ASOUNDCONF
			echo '		1.0 '$VOLRIGHT          >>$ASOUNDCONF
			echo '		1.1 '$VOLRIGHT          >>$ASOUNDCONF
			echo '	}'                          >>$ASOUNDCONF
			;;
		swap)
			echo '	# swap 0 = left, 1 = right' >>$ASOUNDCONF
			echo '	ttable {'                   >>$ASOUNDCONF
			echo '		0.1 '$VOLLEFT           >>$ASOUNDCONF
			echo '		1.0 '$VOLRIGHT          >>$ASOUNDCONF
			echo '	}'                          >>$ASOUNDCONF
			;;
	esac

	echo '}'                           >>$ASOUNDCONF
}

pcp_httpd_query_string

VOLLEFT="0."$VOLUMELEFT
if [ $VOLUMELEFT -eq 0 ]; then
	VOLLEFT=0
elif [ $VOLUMELEFT -lt 10 ]; then
	VOLLEFT="0.0"$VOLUMELEFT
elif [ $VOLUMELEFT -ge 100 ]; then
	VOLLEFT=1
fi

VOLRIGHT="0."$VOLUMERIGHT
if [ $VOLUMERIGHT -eq 0 ]; then
	VOLRIGHT=0
elif [ $VOLUMERIGHT -lt 10 ]; then
	VOLRIGHT="0.0"$VOLUMERIGHT
elif [ $VOLUMERIGHT -ge 100 ]; then
	VOLRIGHT=1
fi

case "$SUBMIT" in
	Write)
		echo '<p class="info">[ INFO ]Writing asound.conf...</p>'
		pcp_write_asound_conf
		;;
	*)
		OPT=0
		;;
esac

#========================================================================================
# Start table
#----------------------------------------------------------------------------------------
echo '<table class="bggrey">'
echo '  <tr>'
echo '    <td>'
echo '      <form name="asound" action="xtras_asoundrc.cgi" method="get" id="asound">'
echo '        <div class="row">'
echo '          <fieldset>'
echo '            <legend>Generate asound.conf</legend>'
echo '            <table class="bggrey percent100">'

echo '              <tr class="even">'
echo '                <td class="column150">'
echo '                  <p class="row">Stereo/Mono/Swap</p>'
echo '                </td>'
echo '                <td class="column210">'
echo '                  <input class="small1" type="radio" name="OPTION" id="WIFI" value="stereo">Stereo&nbsp;'
echo '                  <input class="small1" type="radio" name="OPTION" id="WIFI" value="mono">Mono&nbsp;'
echo '                  <input class="small1" type="radio" name="OPTION" id="WIFI" value="swap">Swap'
echo '                </td>'
echo '                <td>'
echo '                  <p class="row">Column 3</p>'
echo '                </td>'
echo '              </tr>'

echo '              <tr class="odd">'
echo '                <td class="column150">'
echo '                  <p class="row">Left channel</p>'
echo '                </td>'
echo '                <td class="column210">'
echo '                  <input class="small2" type="text" id="VOLUMELEFT" name="VOLUMELEFT" value="'$VOLUMELEFT'">&nbsp;Volume (1-100)'
echo '                </td>'
echo '                <td class="column150">'
echo '                  <p class="row">Column 3</p>'
echo '                </td>'
echo '              </tr>'

echo '              <tr class="even">'
echo '                <td class="column150">'
echo '                  <p class="row">Right channel</p>'
echo '                </td>'
echo '                <td class="column210">'
echo '                  <input class="small2" type="text" id="VOLUMERIGHT" name="VOLUMERIGHT" value="'$VOLUMERIGHT'">&nbsp;Volume (1-100)'
echo '                </td>'
echo '                <td class="column150">'
echo '                  <p class="row">Column 3</p>'
echo '                </td>'
echo '              </tr>'

echo '              </tr>'
echo '              <tr>'
echo '                <td colspan="3">'
echo '                  <input type="submit" name="SUBMIT" value="Write">'
echo '                </td>'
echo '              </tr>'
echo '            </table>'
echo '          </fieldset>'
echo '        </div>'
echo '      </form>'
echo '    </td>'
echo '  </tr>'
echo '</table>'

#========================================================================================
# Current asound.conf
#----------------------------------------------------------------------------------------
echo '<table class="bggrey">'
echo '  <tr>'
echo '    <td>'
echo '      <form name="asound_conf" method="get">'
echo '        <div class="row">'
echo '          <fieldset>'
echo '            <legend>Current asound.conf</legend>'
echo '            <table class="bggrey percent100">'
echo '              <tr class="odd">'
echo '                <td>'

                        pcp_textarea_inform "none" "cat $ASOUNDCONF" 150

echo '                </td>'
echo '              </tr>'



echo '            </table>'
echo '          </fieldset>'
echo '        </div>'
echo '      </form>'
echo '    </td>'
echo '  </tr>'


echo '              <tr class="odd">'
echo '                <td class="column150 center">'
echo '                  <form id="Restart" name="Restart" action="restartsqlt.cgi" method="get">'
echo '                    <input type="submit" value="Restart" />'
echo '                  </form>'
echo '                </td>'
echo '                <td class="column150">'
echo '                  <p class="row">Restart Squeezelite</p>'
echo '                </td>'
echo '              </tr>'

echo '</table>'
#----------------------------------------------------------------------------------------

pcp_footer
pcp_refresh_button

echo '</body>'
echo '</html>'