#!/bin/sh

# Version: 0.01 2015-04-30 GE
#   Original version.

. pcp-lms-functions
. pcp-functions
pcp_variables
. $CONFIGCFG

pcp_html_head "xtras" "GE"

pcp_banner
pcp_running_string
pcp_xtras

#========================================================================================
echo '<h1>squeezelite/pCP toolbar</h1>'
#----------------------------------------------------------------------------------------
echo '<p><b>Note: </b>This toolbar is generated by querying LMS for the available squeezelite players.</p>'
echo '<p>I think we should add the option to squeezelite to set the player to piCorePlayer.</p>'
pcp_picoreplayers

#========================================================================================
echo '<h1>uptime routines test</h1>'
#----------------------------------------------------------------------------------------
echo '<p><b>Note: </b>Still testing what happens for day, hour or minute = 1.</p>'
echo '<table class="bggrey">'
echo '  <tr>'
echo '    <td>'
echo '      <div class="row">'
echo '        <fieldset>'
echo '          <legend>Raspberry Pi</legend>'
echo '          <table class="bggrey percent100">'
#----------------------------------------------------------------------------------------
echo '            <tr class="even">'
echo '              <td class="column150">'
echo '                <p>Uptime (secs):</p>'
echo '              </td>'
echo '              <td class="column150">'
echo '                <p>'$(pcp_uptime_seconds)'</p>'
echo '              </td>'
echo '              <td class="column150">'
echo '                <p>Uptime (mins):</p>'
echo '              </td>'
echo '              <td class="column150">'
echo '                <p>'$(pcp_uptime_minutes)'</p>'
echo '              </td>'
echo '              <td colspan="2">'
echo '                <p>'$(pcp_uptime_days)'</p>'
echo '              </td>'
echo '            </tr>'
#----------------------------------------------------------------------------------------
echo '          </table>'
echo '        </fieldset>'
echo '      </div>'
echo '    </td>'
echo '  </tr>'
echo '</table>'

#========================================================================================
echo '<h1>Favorites toolbar</h1>'
#----------------------------------------------------------------------------------------
echo '<p><b>Note: </b>Your favorites should be appearing in the toolbar below.</p>'
pcp_favorites
#----------------------------------------------------------------------------------------

#========================================================================================
echo '<h1>Common buttons test</h1>'
#----------------------------------------------------------------------------------------
echo '<p><b>Note: </b>The commonly used buttons should appear below.</p>'
pcp_go_main_button
pcp_refresh_button
pcp_go_back_button
pcp_reboot_button
#----------------------------------------------------------------------------------------

pcp_footer
echo '</body>'
echo '</html>'