#!/bin/sh

# Version: 0.01 2016-01-07 SBP
#	Original.

PNAME="Shairport-sync"
DESC="Shairport-sync player"
DAEMON=/mnt/mmcblk0p2/tce/shairport-sync

# Not used.
# ON_START="echo power 0 | nc 192.168.1.101 9090"
# ON_STOP="echo power 1 | nc 192.168.1.101 9090"
# -B "$ON_START" -E "$ON_STOP"

# Read from config file
. /usr/local/sbin/config.cfg

case "$1" in
        start)
                echo "Starting $DESC: $PNAME..."
                start-stop-daemon --start --quiet --exec $DAEMON \
                                  -- -a "$NAME" -o alsa -S soxr -d -D -R \
                                  -- -d "$OUTPUT"
                ;;
        stop)
                echo "Stopping $DESC: $PNAME..."
                start-stop-daemon --stop --quiet --exec $DAEMON
                ;;
        restart)
                echo "Restarting $DESC..."
                $0 stop
                sleep 1
                $0 start
                ;;
        status)
                # Check if shairport-sync daemon is running
                PID=$(ps -ef | grep $DAEMON | grep -v grep | awk '{ print $1 }')
                if [ 0$PID -gt 0 ]; then
                        echo "$PNAME is running."
                        exit 0
                else
                        echo "$PNAME not running."
                        exit 1
                fi
                ;;
        *)
                echo
                echo -e "Usage: $0 [start|stop|restart|status]"
                echo
                exit 1
                ;;
esac

exit 0
