#!/bin/sh

# Version: 0.02 2014-10-07 GE
#	Force now always kills squeezelite daemon.
#	Added support for spaces in player name. (I don't understand why it works!)
#	Trimmed sleep times down to 1 second in Restart and Force.

# Version: 0.01 2014-06-27 GE
#	Original.

#set -x

PNAME=Squeezelite
DESC="Squeezelite player"
DAEMON=/mnt/mmcblk0p2/tce/squeezelite-armv6hf
PIDFILE=/var/run/squeezelite.pid

# Read from config file
. /usr/local/sbin/config.cfg

# Check if variable is present then add the correct option in front
[ X"" != X"$NAME" ]        && NAME="$NAME"							# <--- Moved "-n" to allow for spaces
[ X"" != X"$OUTPUT" ]      && OUTPUT="-o $OUTPUT"
[ X"" != X"$ALSA_PARAMS" ] && ALSA_PARAMS="-a "$ALSA_PARAMS""
[ X"" != X"$BUFFER_SIZE" ] && BUFFER_SIZE="-b $BUFFER_SIZE"
[ X"" != X"$_CODEC" ]      && _CODEC="-c $_CODEC"
[ X"" != X"$PRIORITY" ]    && PRIORITY="-p $PRIORITY"
[ X"" != X"$MAX_RATE" ]    && MAX_RATE="-r $MAX_RATE"
[ X"" != X"$UPSAMPLE" ]    && UPSAMPLE="-R $UPSAMPLE"
[ X"" != X"$MAC_ADDRESS" ] && MAC_ADDRESS="-m $MAC_ADDRESS"
[ X"" != X"$SERVER_IP" ]   && SERVER_IP="-s $SERVER_IP"
[ X"" != X"$LOGLEVEL" ]    && LOGLEVEL="-d $LOGLEVEL"
[ X"" != X"$DSDOUT" ]      && DSDOUT="-D $DSDOUT"
[ X"" != X"$VISULIZER" ]   && VISULIZER="-V $VISULIZER"
[ X"" != X"$OTHER" ]       && OTHER="$OTHER"
[ X"" != X"$LOGFILE" ]     && LOGFILE="-f /mnt/sda1/$LOGFILE"

case "$1" in
	start)
		if [ -f $PIDFILE ]; then
			echo "$PNAME already running."
			exit 1
		fi
		echo "Starting $DESC: $PNAME..."
		start-stop-daemon --start --quiet -b -m -p $PIDFILE --exec $DAEMON -- -n "$NAME" $OUTPUT $ALSA_PARAMS $BUFFER_SIZE $_CODEC $PRIORITY $MAX_RATE $UPSAMPLE $MAC_ADDRESS $SERVER_IP $LOGLEVEL $DSDOUT $VISULIZER $OTHER $LOGFILE
		;;
	stop)
		if [ ! -f $PIDFILE ]; then
			echo "$PNAME is not running."
			exit 1
		fi
		echo "Stopping $DESC: $PNAME..."
		start-stop-daemon --stop --quiet -p $PIDFILE
		sudo rm -f $PIDFILE
		;;
	restart)
		echo "Restarting $DESC..."
		$0 stop
		sleep 1
		$0 start
		;;
	force)
		# Force should only be used for testing purposes.
		echo "Forcing a restart of $PNAME..."
		if [ -f $PIDFILE ]; then
			sudo kill `cat $PIDFILE`
			sudo rm -f $PIDFILE
		fi
		sudo ps | grep squeezelite-armv6hf | grep -v grep | awk '{print $1}' | xargs kill -9
		sleep 1
		$0 start
		;;
	status)
		# Possibly should check for squeezelite daemon as well?
		if [ -f  $PIDFILE ]; then
			echo "$PNAME is running."
			exit 0
		else
			echo "$PNAME not running."
			exit 1
		fi
		;;
	*)
		echo
		echo -e "Usage: $0 [start|stop|restart|force|status]"
		echo
		exit 1
		;;
esac

exit 0
