#!/bin/sh
#set -x

 
PNAME=Squeezelite
DESC="Squeezelite player"
DAEMON=/mnt/mmcblk0p2/tce/squeezelite-armv6hf
PIDFILE=/var/run/squeezelite.pid

# Read from config file
. /usr/local/sbin/config.cfg

# Check if variable is present then add the correct option in front
[ X"" != X"$NAME" ]        && NAME="-n $NAME"
[ X"" != X"$OUTPUT" ]      && OUTPUT="-o $OUTPUT"
[ X"" != X"$ALSA_PARAMS" ] && ALSA_PARAMS="-a "$ALSA_PARAMS""
[ X"" != X"$BUFFER_SIZE" ] && BUFFER_SIZE="-b $BUFFER_SIZE"
[ X"" != X"$_CODEC" ]      && _CODEC="-c $_CODEC"
[ X"" != X"$PRIORITY" ]    && PRIORITY="-p $PRIORITY"
[ X"" != X"$MAX_RATE" ]    && MAX_RATE="-r $MAX_RATE"
[ X"" != X"$UPSAMPLE" ]    && UPSAMPLE="-R $UPSAMPLE"
[ X"" != X"$MAC_ADDRESS" ] && MAC_ADDRESS="-m $MAC_ADDRESS"
[ X"" != X"$SERVER_IP" ]   && SERVER_IP="-s $SERVER_IP"
[ X"" != X"$LOGLEVEL" ]    && LOGLEVEL="-d $LOGLEVEL"
[ X"" != X"$DSDOUT" ]      && DSDOUT="-D $DSDOUT"
[ X"" != X"$VISULIZER" ]   && VISULIZER="-V $VISULIZER"
[ X"" != X"$OTHER" ]       && OTHER="$OTHER"
[ X"" != X"$LOGFILE" ]     && LOGFILE="-f /mnt/sda1/$LOGFILE"

OPTIONS="$NAME $OUTPUT $ALSA_PARAMS $BUFFER_SIZE $_CODEC $PRIORITY $MAX_RATE $UPSAMPLE $MAC_ADDRESS $SERVER_IP $LOGLEVEL $DSDOUT $VISULIZER $OTHER $LOGFILE"

case "$1" in
	start)
		if [ -f $PIDFILE ]; then
			echo "$PNAME already running."
			exit 1
		fi
		echo "Starting $DESC: $PNAME..."
		start-stop-daemon --start --quiet -b -m -p $PIDFILE --exec $DAEMON -- $OPTIONS
		;;
	stop)
		if [ ! -f $PIDFILE ]; then
			echo "$PNAME is not running."
			exit 1
		fi
		echo "Stopping $DESC: $PNAME..."
		start-stop-daemon --stop --quiet -p $PIDFILE
		sudo rm -f $PIDFILE
		;;
	restart)
		echo "Restarting $DESC..."
		$0 stop
		sleep 3
		$0 start
		;;
	force)
                echo "Attempting to force a restart of $PNAME..."
		if [ -f $PIDFILE ]; then
                        sudo kill `cat $PIDFILE`
			sudo rm -f $PIDFILE
		else
			sudo ps -ef | grep squeeze | grep -v grep | awk '{print $1}' | xargs kill -9
		fi
		sleep 5
		$0 start
		;;
	status)
		if [ -f  $PIDFILE ]; then
			echo "$PNAME is running with options: $OPTIONS"
			exit 0
		else
			echo "$PNAME not running."
			exit 1
		fi
		;;
	*)
		echo
		echo -e "Usage: $0 [start|stop|restart|force|status]"
		echo
		exit 1
		;;
esac

exit 0

